/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.PerfilControler;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Vinícius
 */
public class NovoPerfilCurricular extends javax.swing.JInternalFrame {

    /**
     * Creates new form NovoPerfilCurricular
     */
    public NovoPerfilCurricular() {
        initComponents();

        PerfilControler c = new PerfilControler(this);

        btSalvar.addActionListener(c);
        btVoltar.addActionListener(c);
        btAtt.addActionListener(c);

    }

    public JCheckBox getCBefF() {
        return CBefF;
    }

    public void setCBefF(JCheckBox CBefF) {
        this.CBefF = CBefF;
    }

    public JCheckBox getCBefI() {
        return CBefI;
    }

    public void setCBefI(JCheckBox CBefI) {
        this.CBefI = CBefI;
    }

    public JCheckBox getCBem() {
        return CBem;
    }

    public void setCBem(JCheckBox CBem) {
        this.CBem = CBem;
    }

    public JButton getBtAtt() {
        return btAtt;
    }

    public void setBtAtt(JButton btAtt) {
        this.btAtt = btAtt;
    }

    public JButton getBtSalvar() {
        return btSalvar;
    }

    public void setBtSalvar(JButton btSalvar) {
        this.btSalvar = btSalvar;
    }

    public JButton getBtVoltar() {
        return btVoltar;
    }

    public void setBtVoltar(JButton btVoltar) {
        this.btVoltar = btVoltar;
    }

    public JComboBox<String> getCbSerieFF() {
        return cbSerieFF;
    }

    public void setCbSerieFF(JComboBox<String> cbSerieFF) {
        this.cbSerieFF = cbSerieFF;
    }

    public JComboBox<String> getCbSerieFI() {
        return cbSerieFI;
    }

    public void setCbSerieFI(JComboBox<String> cbSerieFI) {
        this.cbSerieFI = cbSerieFI;
    }

    public JComboBox<String> getCbSerieM() {
        return cbSerieM;
    }

    public void setCbSerieM(JComboBox<String> cbSerieM) {
        this.cbSerieM = cbSerieM;
    }

    public JComboBox<String> getCbTurmaFF() {
        return cbTurmaFF;
    }

    public void setCbTurmaFF(JComboBox<String> cbTurmaFF) {
        this.cbTurmaFF = cbTurmaFF;
    }

    public JComboBox<String> getCbTurmaFI() {
        return cbTurmaFI;
    }

    public void setCbTurmaFI(JComboBox<String> cbTurmaFI) {
        this.cbTurmaFI = cbTurmaFI;
    }

    public JComboBox<String> getCbTurmaM() {
        return cbTurmaM;
    }

    public void setCbTurmaM(JComboBox<String> cbTurmaM) {
        this.cbTurmaM = cbTurmaM;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    public void setTxtNome(JTextField txtNome) {
        this.txtNome = txtNome;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CBefI = new javax.swing.JCheckBox();
        CBem = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cbSerieFI = new javax.swing.JComboBox<>();
        cbSerieM = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbTurmaFI = new javax.swing.JComboBox<>();
        cbTurmaM = new javax.swing.JComboBox<>();
        btAtt = new javax.swing.JButton();
        CBefF = new javax.swing.JCheckBox();
        cbTurmaFF = new javax.swing.JComboBox<>();
        cbSerieFF = new javax.swing.JComboBox<>();
        btSalvar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Perfil Curricular"));

        txtNome.setEditable(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel17.setText("Nome");

        CBefI.setText("Ensino Fundamental Inicial");
        CBefI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBefIActionPerformed(evt);
            }
        });

        CBem.setText("Ensino Médio");
        CBem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBemActionPerformed(evt);
            }
        });

        jLabel1.setText("Série");

        cbSerieFI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1°", "2°", "3°", "4°", " ", " " }));
        cbSerieFI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSerieFIActionPerformed(evt);
            }
        });

        cbSerieM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1°", "2°", "3°", " " }));
        cbSerieM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSerieMActionPerformed(evt);
            }
        });

        jLabel2.setText("Turma");

        cbTurmaFI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));
        cbTurmaFI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTurmaFIActionPerformed(evt);
            }
        });

        cbTurmaM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", " " }));
        cbTurmaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTurmaMActionPerformed(evt);
            }
        });

        btAtt.setText("Atualizar");
        btAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAttActionPerformed(evt);
            }
        });

        CBefF.setText("Ensino Fundamental Final");
        CBefF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBefFActionPerformed(evt);
            }
        });

        cbTurmaFF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));
        cbTurmaFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTurmaFFActionPerformed(evt);
            }
        });

        cbSerieFF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5°", "6°", "7°", "8°", " ", " " }));
        cbSerieFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSerieFFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(txtNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAtt))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(CBem)
                        .addGap(157, 157, 157)
                        .addComponent(cbSerieM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTurmaM, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(CBefI)
                        .addGap(98, 98, 98)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSerieFI, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbTurmaFI, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(CBefF)
                        .addGap(98, 98, 98)
                        .addComponent(cbSerieFF, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbTurmaFF, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAtt))
                        .addGap(44, 44, 44)
                        .addComponent(CBefI))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSerieFI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTurmaFI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(CBefF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTurmaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSerieM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBem)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSerieFF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTurmaFF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btVoltar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void cbSerieFIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSerieFIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSerieFIActionPerformed

    private void cbSerieMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSerieMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSerieMActionPerformed

    private void CBefIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBefIActionPerformed
        if (CBefI.isSelected()) {
            txtNome.setText("");

            CBefF.setEnabled(false);
            cbSerieFF.setEnabled(false);
            cbTurmaFF.setEnabled(false);

            CBem.setEnabled(false);
            cbSerieM.setEnabled(false);
            cbTurmaM.setEnabled(false);
        } else {
            txtNome.setText("");

            CBem.setEnabled(true);
            cbSerieM.setEnabled(true);
            cbTurmaM.setEnabled(true);
            
            CBefI.setEnabled(true);
            cbSerieFI.setEnabled(true);
            cbTurmaFI.setEnabled(true);

            CBefF.setEnabled(true);
            cbSerieFF.setEnabled(true);
            cbTurmaFF.setEnabled(true);

        }
    }//GEN-LAST:event_CBefIActionPerformed

    private void CBemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBemActionPerformed
        if (CBem.isSelected()) {
            txtNome.setText("");

            CBefI.setEnabled(false);
            cbSerieFI.setEnabled(false);
            cbTurmaFI.setEnabled(false);

            CBefF.setEnabled(false);
            cbSerieFF.setEnabled(false);
            cbTurmaFF.setEnabled(false);

        } else {
            txtNome.setText("");

            CBem.setEnabled(true);
            cbSerieM.setEnabled(true);
            cbTurmaM.setEnabled(true);
            
            CBefI.setEnabled(true);
            cbSerieFI.setEnabled(true);
            cbTurmaFI.setEnabled(true);

            CBefF.setEnabled(true);
            cbSerieFF.setEnabled(true);
            cbTurmaFF.setEnabled(true);
        }
    }//GEN-LAST:event_CBemActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

    }//GEN-LAST:event_btSalvarActionPerformed

    private void cbTurmaFIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTurmaFIActionPerformed


    }//GEN-LAST:event_cbTurmaFIActionPerformed

    private void cbTurmaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTurmaMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTurmaMActionPerformed

    private void btAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAttActionPerformed

    }//GEN-LAST:event_btAttActionPerformed

    private void CBefFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBefFActionPerformed

        if (CBefF.isSelected()) {
            txtNome.setText("");

            CBefI.setEnabled(false);
            cbSerieFI.setEnabled(false);
            cbTurmaFI.setEnabled(false);

            CBem.setEnabled(false);
            cbSerieM.setEnabled(false);
            cbTurmaM.setEnabled(false);

        } else {
            txtNome.setText("");

            CBem.setEnabled(true);
            cbSerieM.setEnabled(true);
            cbTurmaM.setEnabled(true);
            
            CBefI.setEnabled(true);
            cbSerieFI.setEnabled(true);
            cbTurmaFI.setEnabled(true);

            CBefF.setEnabled(true);
            cbSerieFF.setEnabled(true);
            cbTurmaFF.setEnabled(true);
        }
    }//GEN-LAST:event_CBefFActionPerformed

    private void cbTurmaFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTurmaFFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTurmaFFActionPerformed

    private void cbSerieFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSerieFFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSerieFFActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBefF;
    private javax.swing.JCheckBox CBefI;
    private javax.swing.JCheckBox CBem;
    private javax.swing.JButton btAtt;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbSerieFF;
    private javax.swing.JComboBox<String> cbSerieFI;
    private javax.swing.JComboBox<String> cbSerieM;
    private javax.swing.JComboBox<String> cbTurmaFF;
    private javax.swing.JComboBox<String> cbTurmaFI;
    private javax.swing.JComboBox<String> cbTurmaM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
