/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JLabel;
import javax.swing.JMenu;
import model.beans.Administrador;
import model.beans.Funcionario;
import view.AcPedagogico;

/**
 *
 * @author Vinícius
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Funcionario funcionario;
    private Administrador administrador;
    private Object usuario;
    private Long id;

    public TelaPrincipal(Object usuario) {

        this.usuario = usuario;
        initComponents();

        setLocationRelativeTo(null);

        if (usuario instanceof Funcionario) {
            this.funcionario = (Funcionario) usuario;
            setId(funcionario.getId());
        }
        if (usuario instanceof Administrador) {
            this.administrador = (Administrador) usuario;
            setId(administrador.getId());
        }
    }

    public TelaPrincipal() {
        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internoFrame = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        nomeUsuarioLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        alterarSenha = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        novoCliente = new javax.swing.JMenuItem();
        listarClientes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        novoPedido = new javax.swing.JMenuItem();
        listarPedidos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        novoProduto = new javax.swing.JMenuItem();
        listarProduto = new javax.swing.JMenuItem();
        menuFuncionario = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuCaixa = new javax.swing.JMenu();
        caixa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        nomeUsuarioLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        nomeUsuarioLabel.setText("Usuário:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeUsuarioLabel)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomeUsuarioLabel)
                .addContainerGap())
        );

        internoFrame.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout internoFrameLayout = new javax.swing.GroupLayout(internoFrame);
        internoFrame.setLayout(internoFrameLayout);
        internoFrameLayout.setHorizontalGroup(
            internoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, internoFrameLayout.createSequentialGroup()
                .addContainerGap(773, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        internoFrameLayout.setVerticalGroup(
            internoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );

        jMenu1.setText("Perfil");

        alterarSenha.setText("Alterar Senha");
        alterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarSenhaActionPerformed(evt);
            }
        });
        jMenu1.add(alterarSenha);

        sair.setText("Sair");
        jMenu1.add(sair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cliente");

        novoCliente.setText("Cadastrar Cliente");
        novoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoClienteActionPerformed(evt);
            }
        });
        jMenu2.add(novoCliente);

        listarClientes.setText("Listar Clientes");
        listarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarClientesActionPerformed(evt);
            }
        });
        jMenu2.add(listarClientes);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pedido");

        novoPedido.setText("Cadastrar Pedido");
        novoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoPedidoActionPerformed(evt);
            }
        });
        jMenu3.add(novoPedido);

        listarPedidos.setText("Listar Pedidos");
        listarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPedidosActionPerformed(evt);
            }
        });
        jMenu3.add(listarPedidos);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Estoque");

        novoProduto.setText("Cadastrar Produtos e Serviços");
        novoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoProdutoActionPerformed(evt);
            }
        });
        jMenu4.add(novoProduto);

        listarProduto.setText("Listar Produtos e Serviços");
        listarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProdutoActionPerformed(evt);
            }
        });
        jMenu4.add(listarProduto);

        jMenuBar1.add(jMenu4);

        menuFuncionario.setText("Funcionários");

        jMenuItem5.setText("Cadastrar Funcionário");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuFuncionario.add(jMenuItem5);

        jMenuBar1.add(menuFuncionario);

        menuCaixa.setText("Caixa");

        caixa.setText("Controle do Caixa");
        caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaActionPerformed(evt);
            }
        });
        menuCaixa.add(caixa);

        jMenuBar1.add(menuCaixa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internoFrame)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internoFrame)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarClientesActionPerformed

    private void listarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarProdutoActionPerformed

    private void alterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarSenhaActionPerformed

    private void novoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoClienteActionPerformed
        NovaPessoa tlCliente = new NovaPessoa();
        internoFrame.add(tlCliente);
        tlCliente.show();
    }//GEN-LAST:event_novoClienteActionPerformed

    private void novoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoPedidoActionPerformed
        TelaCadastroPedido tlPedido = new TelaCadastroPedido();
        internoFrame.add(tlPedido);
        tlPedido.show();
    }//GEN-LAST:event_novoPedidoActionPerformed

    private void listarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarPedidosActionPerformed

    private void novoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoProdutoActionPerformed
        AcPedagogico telaCadastroProduto = new AcPedagogico();
        internoFrame.add(telaCadastroProduto);
        telaCadastroProduto.show();
    }//GEN-LAST:event_novoProdutoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void caixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarSenha;
    private javax.swing.JMenuItem caixa;
    private javax.swing.JDesktopPane internoFrame;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem listarClientes;
    private javax.swing.JMenuItem listarPedidos;
    private javax.swing.JMenuItem listarProduto;
    private javax.swing.JMenu menuCaixa;
    private javax.swing.JMenu menuFuncionario;
    private javax.swing.JLabel nomeUsuarioLabel;
    private javax.swing.JMenuItem novoCliente;
    private javax.swing.JMenuItem novoPedido;
    private javax.swing.JMenuItem novoProduto;
    private javax.swing.JMenuItem sair;
    // End of variables declaration//GEN-END:variables

    public Funcionario getFuncionario() {
        return funcionario;
    }

    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

    public Object getUsuario() {
        return usuario;
    }

    public void setUsuario(Object usuario) {
        this.usuario = usuario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public JMenu getMenuCaixa() {
        return menuCaixa;
    }

    public JMenu getMenuFuncionario() {
        return menuFuncionario;
    }

    public JLabel getNomeUsuarioLabel() {
        return nomeUsuarioLabel;
    }

    public void setNomeUsuarioLabel(JLabel nomeUsuarioLabel) {
        this.nomeUsuarioLabel = nomeUsuarioLabel;
    }

}
